:doctitle:
:doccode: m2o-main-prod-028
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: November 2023

= The Boilerplate Utility
=== Using the automated online utility: model2owl-boilerplate

To use model2owl without installing or executing anything locally, the online https://github.com/meaningfy-ws/model2owl-boilerplate[model2owl boilerplate utility] was created. The instructions on how to use it are given in the repositories README.md file as well as below.

The utility uses model2owl to transform a UML model into a formal OWL ontology, a SHACL shape, a conventions report, and glossary, based on established UML conventions.

== Getting Started
The main steps are as follows:

. Fork this repository
. Put your UML model/models export (XML file) in the *implementation folder*
. Configure model2owl using the config folder
. Change the GitHub action script provided to include your ontologies

== Naming Conventions

=== Folders:

Folder names should not contain spaces. They may contain underscores or hyphens.

=== The Export File:

The name of the UML model export file should have a _CM suffix in it: e.g., "mymodel_CM.xml".

== Folder Structure Conventions

To add a new UML model follow this folder structure:

----
implementation
        |___firstModel
                |___model2owl-config
                |___xmi_conceptual_model
----


== Adding a UML model

* Create a folder under implementation with the name of the UML model following the naming conventions.
* Create xmi_conceptual_model folder inside the folder created at the previous step
* Put the UML export in the xmi_conceptual_model folder following the naming conventions

== Adding model2owl config

* Copy model2owl-config folder into UML model implementation folder created at the previous step
* Configure model2owl using the files inside model2owl-config folder

== Adjusting the GitHub actions

In the .GitHub folder in the forked repository, the action script that transforms the UML model/models is:

*transform_with_model2owl.yml*

=== Configure the trigger for this action by changing the following lines:

----
    paths:
      - "implementation/demo_ontology/xmi_conceptual_model/demo_ontology_CM.xml"
      - "implementation/demo_ontology/xmi_conceptual_model/demo_ontology_module_CM.xml"

----
If a change is detected in any the files that are included in the paths config, it will trigger this GitHub action. The paths should be to the UML model export file.

Configure which of the implementation should be included by changing the AVAILABLE_IMPLEMENTATIONS variable inside the action script.

----
AVAILABLE_IMPLEMENTATIONS=(demo_ontology demo_ontology_module)
----

NOTE: Search the script for all references to this variable declaration as it has multiple usage and change the value accordingly. The values in the list should be the folder names created for the UML model under the implementation folder.

----
Example:

implementation
        |___modelOne
        |___modelTwo

To include both models for generating the convention report and glossary the variable should be
AVAILABLE_IMPLEMENTATIONS=(modelOne modelTwo)
----

== Output
The output is generated automatically by the GitHub action scripts. Each of the scripts does an automatic commit on the branch that it was executed from.The scripts will generate folders and transformation files automatically under the structure shown below.

NOTE: To see the output, a git pull must be executed after the GitHub action has run successfully.

=== Output folders structure and content
Glossaries are stored at the top level of this project, outside the implementation folder, and will contain the individual glossaries for the UML model, and a unified glossary if there is more than one UML model processed by the GitHub action scripts.

----
.github
glossary
|__static  -> folder to hold css and js neccesary for the glossary
|__modelOne_CM_glossary.html
|__modelTwo_CM_glossary.html
|__ontologies_combined_glossary.html   -> combined glossary
implementation
model2owl-config
----

The formal OWL ontology and a SHACL shape can be found inside each UML model folder under the specific folders described below.

----
    implementation
        |___modelOne
                |__conventions_report
                |       |__static -> folder to hold css and js neccesary for the convention report
                |       |__modelOne_CM-convention-report.html
                |__owl_ontology
                |       |__modelOne_CM_core.rdf
                |       |__modelOne_CM_core.ttl
                |       |__modelOne_CM_restrictions.rdf
                |       |__modelOne_CM_restrictions.ttl
                |__shacl_shapes
                |       |__modelOne_CM_shapes.rdf
                |       |__modelOne_CM_shapes.rdf
                |___model2owl-config
                |___xmi_conceptual_model
        |___modelTwo
----



include::partial$feedback.adoc[]