:doctitle: The model2owl Project
:doccode: m2o-main-prod-001
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: November 2023

"model2owl" is a tool for transforming human-readable semantic models into machine-readable OWL (core and restriction) files and SHACL shapes. It takes the human-readable input in UML form, applies modelling conventions, transformation rules, and methods of verification to it, and outputs it in machine-readable OWL format.

The following topics are included in this version of the model2owl documentation:

* xref:intro_overview.adoc[Introduction] +
An introduction to the model2owl project


* xref:terminology.adoc[Important Terminology] +
Terminology

== UML Conventions

* xref:uml/conceptual-model-conventions.adoc[The UML Model Conventions] +
A list and descriptions of the UML model conventions

== Transformation Rules

* xref:transformation/uml2owl-transformation.adoc[Introduction] +
An introduction to the transformation rules
* xref:transformation/transf-rules1.adoc[UML Classes and Attributes] +
Transformation of UML classes and attributes
* xref:transformation/transf-rules2.adoc[Connectors] +
Transformation of connectors
* xref:transformation/transf-rules3.adoc[Data Types] +
Transformation of UML Data Types
* xref:transformation/transf-rules4.adoc[Descriptors and Tags] +
Transformation of UML descriptors and tags

== Checkers (Validation)

* xref:checkers/model2owl-checkers.adoc[UML Convention Checking Rules] +
The UML convention checking inventory

== Performing Transformations
* xref:local.adoc[Local machine] +
Performing Transformations on a Local Machine
* xref:boiler.adoc[The boilerplate utility] +
Performing transformations online using the boilerplate utility


include::partial$feedback.adoc[]