//[[sec:introduction]]

= Introduction to the model2owl Project

== Background

#highlighted words to sort out refs#

The model2owl pipeline transforms the UML diagram created by business stakeholders into OWL (core and restriction) files and shacl files to be used by machines. (to be expanded on)

In the https://docs.ted.europa.eu/epo-home/ePO_Arch_Design.html[planning and development] of the eProcurement Ontology Project, it was decided to represent the conceptual model in *Unified Modelling Language* (UML) #(ref:uml-userguide -book)#. UML is a language that represents concepts visually, thereby facilitating understanding and a common conceptualisation of the model amongst stakeholders.

UML is closer to the programming languages in which enterprise applications are implemented than other more logic-oriented approaches, and generally, the primary application of UML for ontology design is in the development of class diagrams for object-oriented software #(fowler2004 -book)#. UML, however, does not define formal semantics that allow consistent or accurate determination of an ontology implementation from class diagrams. Semantics, therefore, may become subject to interpretation firstly by stakeholders involved in the development process, and secondly, by users in application and integration tasks #(grunninger2003 -book)#.

To achieve consistency, this project provides a set of clear transformation rules, a set of modelling conventions, methods of verification, and an automated process of conversion designed to minimise variations in interpretation. #(This is my sentence as the initial documentation described issues but didn't state a solution  or resolution)#.

== model2owl in an eProcurement context

The documentation provides a working specification, and guidelines and conventions for the eProcurement conceptual model, and describes how the model qualifies as suitable input for the transformation scripts that generate the formal eProcurement ontology.

The UML Conceptual Model of the eProcurement domain provides the source from which the formal eProcurement ontology is derived through a model transformation process. It automates the generation of the formal ontology in RDF format [xref:references.adoc#ref:rdf11[rdf11]], from the XMI (v.2.5.1) serialisation [xref:references.adoc#ref:xmi2.5.1[xmi2.5.1]] of a UML (v.2.5) model [xref:references.adoc#ref:uml2.5[uml2.5]], provided that xref:transformation/uml2owl-transformation.adoc[a set of clear transformation rules] is established, and xref:uml/conceptual-model-conventions.adoc[a set of modelling conventions] is respected.

This documentation also provides the UML modelling constraints and a set of conventional and technical recommendations for naming and structuring the UML class diagram elements. These elements are packages, classes, data types, enumerations, enumeration items, class attributes, association relations and dependency relations. More contextual information is provided in the subsections of the xref::uml/conceptual-model-conventions.adoc[UML conventions specification].

[[sec:requirements]]
=== eProcurement conceptual model requirements

The eProcurement conceptual model must fulfil four fundamental objectives:

It must
* facilitate understanding of the represented system.
* convey system details between team members and external stakeholders efficiently.
* provide a point of reference for system designers to gather system specifications and documentation.
* serve as input for the development of a formal model.

To support these objectives, a conceptual model should fulfil the following requirements:

* be available to all team members for collaboration and iteration.
* be easily changeable to reflect up-to-date information.
* contain both visual and written forms of diagramming, to  explain the abstract concepts better.
* establish terms and concepts that will be used throughout the project.
* define said terms and concepts.
* provide a basic structure for the entities of the project.
* reduce ambiguity while maintaining simple and concise encoding.

The links here provide more information for both  xref:business.adoc[business] and xref:technical.adoc[technical] users.

