== Overview

The creation of the  https://docs.ted.europa.eu/epo-home/ePO_Arch_Design.html[eProcurement Ontology] requires collaborative discussions and consensus among various experts in the procurement domain to develop a conceptual model, while the tangible outcomes of the eProcurement Ontology, comprising an OWL-expressed ontology, a series of SHACL shapes, and a glossary, iare typically developed by semantic web specialists.


////
In the https://docs.ted.europa.eu/epo-home/ePO_Arch_Design.html[planning and development] of the eProcurement Ontology Project, it was decided to represent the conceptual model in https://www.amazon.com/Unified-Modeling-Language-User-Guide/dp/0321267974[Unified Modelling Language (UML)]. UML is a language that represents concepts visually, thereby facilitating understanding and a common conceptualisation of the model amongst stakeholders.


UML is closer to the programming languages in which enterprise applications are implemented than other more logic-oriented approaches, and generally, the primary application of UML for ontology design is in the development of class diagrams for object-oriented software (for more information, see https://www.amazon.com/UML-Distilled-Standard-Modeling-Language/dp/0321193687[here]).
////

To maintain broader public interaction and discussion, and continue the development of these artifacts, the ePO model2owl working group opted for an intermediary representation, unified modeling language (UML). UML allows participation in the development process by technical and non-technical parties as it holds widespread recognition in the eProcurement domain, and is also comprehensible to a wider audience. In addition, tools exist that facilitate the generation of diagrams on top of visual representations, facilitating discussion by all interested groups.

////
UML, however, does not necessarily define formal semantics as consistently or accurately as required to support the implementation of an ontology from class diagrams. Semantics, therefore, may become subject to interpretation by both stakeholders involved in the development process, and by users performing application and integration tasks (for more information, see https://link.springer.com/chapter/10.1007/978-3-540-24744-9_14[here]).
////

*model2OWL* adheres to https://semiceu.github.io/style-guide/1.0.0/index.html[semantic conventions], which enables operation within a unified UML model. This model serves as the single source of truth, and through automated processes, essential artifacts such as a glossary, an OWL ontology, and SHACL shapes can be generated. Embracing a single source of truth, and automating artifact generation, significantly reduces administrative overhead in each development cycle.

// #insert some examples: contract conclusion/ different country rules/ adherence to legislation etc#

To generate machine-readable OWL (core and restriction) files and SHACL shapes, the model2owl tool does the following:

It takes the human-readable input in UML form, and in an automated conversion process, applies sets of modelling conventions, transformation rules, and methods of verification to it before generating the output.

The output artifacts are defined by the https://semiceu.github.io/style-guide/1.0.0/terminological-clarifications.html#sec:what-is-a-semantic-data-specification[semic conventions] as a specification, the significance of which is that it ensures that all relevant stakeholders generate data that adheres to the agreed model. The data is structured in the form of a graph that follows https://semiceu.github.io/style-guide/1.0.0/style-guide-whole.html#sec:pc-r1[Linked Data] principles.

== model2owl in an eProcurement context

This documentation provides a working specification, guidelines, and conventions for the eProcurement conceptual model, and describes how the model qualifies as suitable input for the transformation scripts that generate the eProcurement ontology.

The UML Conceptual Model of the eProcurement domain provides the source from which the formal eProcurement ontology is derived. The model2owl transformation process automates the generation of the formal ontology in https://www.w3.org/TR/2014/REC-rdf-schema-20140225/[RDF format], from the http://www.omg.org/spec/XMI/2.5.1[XMI (v.2.5.1) serialisation] of the data, provided that xref:transformation/uml2owl-transformation.adoc[a set of clear transformation rules] is established, and xref:uml/conceptual-model-conventions.adoc[a set of modelling conventions] is respected.

This documentation also describes the UML modelling constraints and a set of conventional and technical recommendations for naming and structuring the UML class diagram elements. These elements include packages, classes, data types, enumerations, enumeration items, class attributes, association relations and dependency relations. More contextual information is provided in the subsections of the xref::uml/conceptual-model-conventions.adoc[UML conventions specification].

In the context of eGovernment digitalisation, the https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2013:175:0001:0008:EN:PDF#:~:text=This%20Directive%20respects%20the%20fundamental,to%20property%20(Article%2017)["once only principle" in EU public administration] on the re-use of public sector information is one of the drivers towards eProcurement, aimed at making public spending more transparent, evidence-oriented, optimised, streamlined and integrated with market conditions. Part of this is the development of an https://docs.ted.europa.eu/EPO/latest/index.html[eProcurement Ontology].

The eProcurement ontology is represented in the human-readable form of a UML conceptual model. Working with the model in this form allows participation in, and discussion between, the following stakeholders, both technical and non-technical:

* Contracting authorities and entities, i.e., buyers, such as public administrations in the EU Member States or EU institutions;

* Economic operators, i.e., suppliers of goods and services such as businesses, entrepreneurs and financial institutions;

* Academia and researchers;

* Media and journalists;

* Auditors and regulators;

* Members of parliaments at regional, national and EU level;

* Standardisation organisations;

* NGOs; and

* Citizens

//#insert graphic of collaboration/ dev process#

To facilitate the digitisation of eProcurement, a machine-readable form of the conceptual model must be produced: the model needs to be converted/ translated into machine-readable OWL files and SHACL shapes.
The model2owl tool has been created to perform this function. It uses a number of xref:technical.adoc[open standards and conventions] in a process that includes strict rules and validation:

* Firstly, the UML must follow certain xref:uml/conceptual-model-conventions.adoc[conventions]
* Secondly, xref:transformation/uml2owl-transformation.adoc[transfer rules] must be applied.
* Thirdly, the resulting output files need to be xref:checkers/model2owl-checkers.adoc[checked and validated].

//#graphic of the high-level technical process with file examples#

To understand the technical process in more depth, see the xref:technical.adoc[Technical Overview].

A more detailed description of the functional and technical overviews can be found in the xref:ePO_Arch_Design.adoc[eProcurement Ontology Architecture and Formalisation Specifications].
////
[[sec:requirements]]
=== eProcurement conceptual model requirements

The eProcurement conceptual model must fulfil four fundamental objectives:

It must

* facilitate understanding of the represented system.
* convey system details between team members and external stakeholders efficiently.
* provide a point of reference for system designers to gather system specifications and documentation.
* serve as input for the development of a formal model.

To support these objectives, a conceptual model should fulfil the following requirements:

* be available to all team members for collaboration and iteration.
* be easily changeable to reflect up-to-date information.
* contain both visual and written forms of diagramming, to  explain the abstract concepts better.
* establish terms and concepts that will be used throughout the project.
* define said terms and concepts.
* provide a basic structure for the entities of the project.
* reduce ambiguity while maintaining simple and concise encoding.

//The links here provide more information for both  xref:business.adoc[business] and xref:technical.adoc[technical] users.

Information on the eProcurement ontology architecture, UML conventions, transfer rules and checkers (validators) can be accessed from the links in the left-hand menu.
////

//#what about github resources?#

include::partial$feedback.adoc[]