:doctitle: Introduction

== The Once Only Principle (TOOP)

In the context of EU eGovernment digitalisation, the https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2013:175:0001:0008:EN:PDF#:~:text=This%20Directive%20respects%20the%20fundamental,to%20property%20(Article%2017)["once only principle" in EU public administration] on the re-use of public sector information is one of the drivers of eProcurement, aimed at making public spending more transparent, evidence-oriented, optimised, streamlined and integrated with market conditions. Part of this is the development of an https://docs.ted.europa.eu/EPO/latest/index.html[eProcurement Ontology].

  
 The eProcurement Ontology provides consistent names, relationships, cardinalities, etc, to all aspects of eProcurement which ensures that the terminology is consistent. Translations into all the EU languages are also treated in this way. This is essential for the resulting data produced during the eProcurement process and made available for public consumption so that searching the data is efficient, and the results accurate, complete and specific.

== model2owl in an eProcurement context

#model2owl is used to produce the core vocabulary of the eProcurement and the different modules that extend this core, like eCatalogue, eContract, eFulfilment, etc. explain process further...#

//The creation of the  https://docs.ted.europa.eu/epo-home/ePO_Arch_Design.html[eProcurement Ontology] requires collaborative discussions and consensus among various experts in the procurement domain to develop a conceptual model, while the tangible outcomes of the eProcurement Ontology, comprising an OWL-expressed ontology, a series of SHACL shapes, and a glossary, are typically developed by semantic web specialists.

== eProcurement conceptual model requirements

The eProcurement conceptual model must fulfil four fundamental objectives:

It must

* facilitate understanding of the represented system.
* convey system details between team members and external stakeholders efficiently.
* provide a point of reference for system designers to gather system specifications and documentation.
* serve as input for the development of a formal model.

To support these objectives, a conceptual model should fulfil the following requirements:

* be available to all team members for collaboration and iteration.
* be easily changeable to reflect up-to-date information.
* contain both visual and written forms of diagramming, to  explain the abstract concepts better.
* establish terms and concepts that will be used throughout the project.
* define said terms and concepts.
* provide a basic structure for the entities of the project.
* reduce ambiguity while maintaining simple and concise encoding.

Information on the eProcurement ontology architecture, UML conventions, transfer rules and checkers (validators) can be accessed from the links in the left-hand menu.
In this section I would talk about how we already use this for eProcurement. Explain that we use this approach to produce the core vocabulary of eProcurement and the different modules that extend this core, like eCatalogue, eContract, eFulfilment etc. (there are many more) 

== Semantic data-specifications for e-procurement

https://github.com/OP-TED/model2owl[model2owl] is a project. Here it is a specific implementation which, in terms of the ePO, honours the specifications published in these documents. 

In short, model2owl is used to generate a semantic data specification from the ePO conceptual model. An open source https://github.com/OP-TED/model2owl[reference implementation] is available here.

The eProcurement ontology is represented in the human-readable form of a UML conceptual model. Working with the model in this form allows participation in, and discussion between, the following stakeholders, both technical and non-technical:

* Contracting authorities and entities, i.e., buyers, such as public administrations in the EU Member States or EU institutions;

* Economic operators, i.e., suppliers of goods and services such as businesses, entrepreneurs and financial institutions;

* Academia and researchers;

* Media and journalists;

* Auditors and regulators;

* Members of parliaments at regional, national and EU level;

* Standardisation organisations;

* NGOs; and

* Citizens

To facilitate the digitisation of eProcurement, a machine-readable form of the conceptual model must be produced: the model needs to be converted/ translated into machine-readable OWL files and SHACL shapes.
The model2owl tool has been created to perform this function. It uses a number of xref:technical.adoc[open standards and conventions] in a process that includes strict rules and validation:

* Firstly, the UML must follow certain xref:uml/conceptual-model-conventions.adoc[conventions]
* Secondly, xref:transformation/uml2owl-transformation.adoc[transfer rules] must be applied.
* Thirdly, the resulting output files need to be xref:checkers/model2owl-checkers.adoc[checked and validated].

To understand the technical process in more depth, see the xref:technical.adoc[Technical Overview].

A more detailed description of the functional and technical overviews can be found in the xref:ePO_Arch_Design.adoc[eProcurement Ontology Architecture and Formalisation Specifications].

To facilitate broader public interaction and discussion, and continue the development of these artifacts, the ePO model2owl working group opted for an intermediary representation, unified modeling language (UML). UML allows participation in the development process by technical and non-technical parties as it holds widespread recognition in the eProcurement domain, and is also comprehensible to a wider audience. In addition, tools exist that facilitate the generation of diagrams on top of visual representations, facilitating discussion by all interested groups.

*model2OWL* adheres to https://semiceu.github.io/style-guide/1.0.0/index.html[semantic conventions], which enables operation within a unified UML model. This model serves as the single source of truth, and through automated processes, essential artifacts such as a glossary, an OWL ontology, and SHACL shapes can be generated. Embracing a single source of truth, and automating artifact generation, significantly reduces administrative overhead in each development cycle.

To generate machine-readable OWL (core and restriction) files and SHACL shapes, the model2owl tool does the following:

It takes the human-readable input in UML form, and in an automated conversion process, applies sets of modelling conventions, transformation rules, and methods of verification to it before generating the output.

The output artifacts are defined by the https://semiceu.github.io/style-guide/1.0.0/terminological-clarifications.html#sec:what-is-a-semantic-data-specification[semic conventions] as a specification, the significance of which is that it ensures that all relevant stakeholders generate data that adheres to the agreed model. The data is structured in the form of a graph that follows https://semiceu.github.io/style-guide/1.0.0/style-guide-whole.html#sec:pc-r1[Linked Data] principles.

//#what about github resources?#

include:partial$feedback.adoc[]