:doctitle: Technical Overview
:doccode: m2o-main-prod-003
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: November 2023

The https://github.com/OP-TED/model2owl/[*model2owl*] project comprises a set of tools for transforming a https://www.omg.org/spec/UML/2.5.1/About-UML[UML (v2.5)] model from its https://www.omg.org/spec/XMI/2.5.1[XMI (v2.5.1)] serialisation into a formal https://www.w3.org/OWL/[OWL ontology], and a https://www.w3.org/TR/shacl/[SHACL shape]. This approach conforms to the https://semiceu.github.io/style-guide/1.0.0/index.html[SEMIC Style Guide] and the https://github.com/meaningfy-ws/model2owl/blob/master/doc/ontology-architecture/ontology-architecture.pdf[eProcurement Ontology Architecture specification].

The UML transformation is performed using https://www.w3.org/TR/xslt-30/[XSLT stylesheets] and assumes that the UML model conforms to the set of conventions outlined in the https://meaningfy-ws.github.io/model2owl-docs/public-review/uml/conceptual-model-conventions.html[ePO UML conventions specification]. This set of UML conventions is aligned with, and extends, the UML conventions specified in the https://semiceu.github.io/style-guide/1.0.0/index.html[SEMIC Style Guide].

The following artifacts are produced from the  UML in the process:

* A *Compliance Report* (for checking the model against the established conventions).
* A *Glossary* (for a quick overview of terminology defined).
* An *OWL 2 lightweight ontology*, suitable as a core vocabulary.
* An *OWL 2 heavyweight ontology* with additional axioms, suitable for reasoning purposes.
* *SHACL data shapes* suitable for representing an application profile.

The documentation (regularly updated) aims to cover the most important aspects when using these tools, including:

* The architectural setup of the project and the ontology.
* The conceptual model conventions to which the UML model should adhere to generate the best possible results.
* The transformation rules applied in the process of conversion.
* The set of validation rules that realise the established conventions (and UML interpretations).

This work is developed in the context of https://github.com/eprocurementontology/eprocurementontology[eProcurement ontology project] financed by the Digital Europe Programme and led by the https://op.europa.eu/en/[Publications Office of the European Union].

The tools can be used on any other ontology that is built according to the https://github.com/meaningfy-ws/model2owl/blob/master/doc/ontology-architecture/ontology-architecture.pdf[modelling architecture] and xref:uml/conceptual-model-conventions.adoc[UML conceptual model conventions] provided.

This specification establishes conventions for the interpretation of the UML-based conceptual model in the eProcurement context.

//#insert technical process graphic#

== Components

* The *specifications* can be found in the xref:architecture/ontology-architecture.adoc[eProcurement ontology architecture and formalisation specifications] document.

* The xref:uml/conceptual-model-conventions.adoc[UML Conceptual Model Conventions] can be accessed via the links in the left-hand menu.

* The xref:transformation/uml2owl-transformation.adoc[Transfer Rules] can also be accessed via the links in the left-hand menu.

* A list and descriptions of the xref:checkers/model2owl-checkers.adoc[Checkers], used for verification.

== Resources

=== Scripts
* *html-conventions-report.xsl* is the script that checks conformance to the technical conventions of the conceptual model.
* *html-model-glossary.xsl* is the script that creates a glossary of the conceptual model.
* *owl-core.xsl* is the transformation script that generates the core OWL ontology.
* *shacl-shapes.xsl* is the transformation script for the SHACL data shape constraints.
* *owl-restrictions.xsl* is the transformation script for the restrictions (on classes and properties) of the OWL ontology.

=== Script unit tests
* *test/unitTest/test-html-conventions-lib* is the location of the unit tests for the script checking the conformance to the technical conventions of the conceptual model.
* *test/unitTest/test-owl-core-lib* is the location of the unit tests for the transformation script for the core OWL ontology.
* *test/unitTest/test-shacl-shape-lib* is the location of the unit tests for the transformation script for the SHACL data shape constraints.
* *test/unitTest/reasoning-layer-lib* is the location of the unit tests for the transformation script for the restrictions of the OWL ontology (classes and properties).

== Performing transformations

There are two ways to perform the transformations:

* xref:local.adoc[Locally], on a machine, and
* Using the xref:boiler.adoc[model2owl boilerplate utility]


////
=== Using the automated online utility: model2owl-boilerplate

To use model2owl without installing or executing anything locally, the online https://github.com/meaningfy-ws/model2owl-boilerplate[model2owl boilerplate utility] has been created. The instructions are given in the repositories README.md file as well as here:

Getting Started:
This project will use model2owl to transform a UML model into a formal OWL ontology, a SHACL shape, a conventions report and glossary based on established UML conventions.

Main steps:

Fork this repository
Put your UML model/models export (XML file) in the implementation folder
Configure model2owl using config folder
Change GitHub action script available to include your ontologies
////

include::partial$feedback.adoc[]


