:doctitle: Technical Overview
:doccode: m2o-main-prod-003
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: November 2023

The https://github.com/OP-TED/model2owl/[*model2owl*] project comprises a set of tools for transforming a https://www.omg.org/spec/UML/2.5.1/About-UML[UML (v2.5)] model from its https://www.omg.org/spec/XMI/2.5.1[XMI (v2.5.1)] serialisation into a formal https://www.w3.org/OWL/[OWL ontology], and a https://www.w3.org/TR/shacl/[SHACL shape]. This approach conforms to the https://semiceu.github.io/style-guide/1.0.0/index.html[SEMIC Style Guide] and the https://github.com/meaningfy-ws/model2owl/blob/master/doc/ontology-architecture/ontology-architecture.pdf[eProcurement Ontology Architecture specification].

The UML transformation is performed using https://www.w3.org/TR/xslt-30/[XSLT stylesheets] and assumes that the UML model conforms to the set of conventions outlined in the https://meaningfy-ws.github.io/model2owl-docs/public-review/uml/conceptual-model-conventions.html[ePO UML conventions specification]. This set of UML conventions is aligned with, and extends, the UML conventions specified in the https://semiceu.github.io/style-guide/1.0.0/index.html[SEMIC Style Guide].

The following artifacts are produced from the  UML in the process:

* A *Compliance Report* (for checking the model against the established conventions).
* A *Glossary* (for a quick overview of terminology defined).
* An *OWL 2 lightweight ontology*, suitable as a core vocabulary.
* An *OWL 2 heavyweight ontology* with additional axioms, suitable for reasoning purposes.
* *SHACL data shapes* suitable for representing an application profile.

The documentation (regularly updated) aims to cover the most important aspects when using these tools, including:

* The architectural setup of the project and the ontology.
* The conceptual model conventions to which the UML model should adhere to generate the best possible results.
* The transformation rules applied in the process of conversion.
* The set of validation rules that realise the established conventions (and UML interpretations).

This work is developed in the context of https://github.com/eprocurementontology/eprocurementontology[eProcurement ontology project] financed by the Digital Europe Programme and led by the https://op.europa.eu/en/[Publications Office of the European Union].

The tools can be used on any other ontology that is built according to the https://github.com/meaningfy-ws/model2owl/blob/master/doc/ontology-architecture/ontology-architecture.pdf[modelling architecture] and xref:uml/conceptual-model-conventions.adoc[UML conceptual model conventions] provided.

This specification establishes conventions for the interpretation of the UML-based conceptual model in the eProcurement context.

//#insert technical process graphic#

== Components

* The *specifications* can be found in the xref:architecture/ontology-architecture.adoc[eProcurement ontology architecture and formalisation specifications] document.

* The xref:uml/conceptual-model-conventions.adoc[UML Conceptual Model Conventions] can be accessed via the links in the left-hand menu.

* The xref:transformation/uml2owl-transformation.adoc[Transfer Rules] can also be accessed via the links in the left-hand menu.

* A list and descriptions of the xref:checkers/model2owl-checkers.adoc[Checkers], used for verification.

== Resources

=== Scripts
* *html-conventions-report.xsl* is the script that checks conformance to the technical conventions of the conceptual model.
* *html-model-glossary.xsl* is the script that creates a glossary of the conceptual model.
* *owl-core.xsl* is the transformation script that generates the core OWL ontology.
* *shacl-shapes.xsl* is the transformation script for the SHACL data shape constraints.
* *owl-restrictions.xsl* is the transformation script for the restrictions (on classes and properties) of the OWL ontology.

=== Script unit tests
* *test/unitTest/test-html-conventions-lib* is the location of the unit tests for the script checking the conformance to the technical conventions of the conceptual model.
* *test/unitTest/test-owl-core-lib* is the location of the unit tests for the transformation script for the core OWL ontology.
* *test/unitTest/test-shacl-shape-lib* is the location of the unit tests for the transformation script for the SHACL data shape constraints.
* *test/unitTest/reasoning-layer-lib* is the location of the unit tests for the transformation script for the restrictions of the OWL ontology (classes and properties).

== Performing transformations

=== Getting started
There are two ways to perform the transformations:

* Locally, on a machine, and
* Online, using the xref:boiler.adoc[model2owl boilerplate utility]

=== Working Locally

==== Introducing the Makefile tool

Makefile is a powerful tool that automates different commands for software projects. It provides a convenient way to define and execute various tasks, such as using source code, generating documentation, running tests, and more.

All commands are executed using the Make build automation tool that needs to be installed if it is not already. Make targets sometimes require optional parameters (see example below). This project uses the default values for the parameters used in the different commands here.

*Example*:
----
# without parameters
make install
# with parameters
make owl-core XMI_INPUT_FILE_PATH=/home/mypc/work/model2owl/file1.xml OUTPUT_FOLDER_PATH=./my-folder
----

*Set-up commands*:

* *get-saxon* - installs saxon in a folder inside the project
* *get-rdflib* - installs the rdflib library
* *get-widoco* - installs saxon in a folder inside the project
* *install* - automatically executes all the commands above
* *create-virtual-env* - creates a virtual environment for the project

*Functional commands*:

* *generate-glossary* - generates a glossary from the UML export (xml/xmi)
** parameters:
*** XMI_INPUT_FILE_PATH - path to the xmi file
*** OUTPUT_GLOSSARY_PATH - path to the folder that stores the output
* *generate-convention-report* - generates the compliance report from the UML export (xml/xmi)
** parameters:
*** XMI_INPUT_FILE_PATH - path to the xmi file
*** OUTPUT_CONVENTION_REPORT_PATH - path to the folder that stores the output
* *owl-core* - generates the lightweight ontology from the UML export (xml/xmi)
** parameters:
*** XMI_INPUT_FILE_PATH - path to the xmi file
*** OUTPUT_FOLDER_PATH - path to the folder that stores the output
* *owl-restrictions* - generates the heavyweight ontology with additional axioms suitable for reasoning purposes from the UML export (xml/xmi)
** parameters:
*** XMI_INPUT_FILE_PATH - path to the xmi file
*** OUTPUT_FOLDER_PATH - path to the folder that stores the output
* *shacl* - generates data shapes suitable for validation from the UML export (xml/xmi)
** parameters:
*** XMI_INPUT_FILE_PATH - path to the xmi file
*** OUTPUT_FOLDER_PATH - path to the folder that stores the output
* *generate-html-docs-from-rdf* - generates html documentation using widoco from a rdf file
** parameters:
*** WIDOCO_RDF_INPUT_FILE_PATH - path to the rdf file
*** OUTPUT_FOLDER_PATH - path to the folder that stores the output
* *merge-xmi* - merges xmis from specific folder
** parameters:
*** FIRST_XMI_TO_BE_MERGED_FILE_PATH - path to the first xmi to be merged. All xmi files need to be in the same folder as the first xmi to be merged.
*** XMI_MERGED_OUTPUT_FOLDER_PATH - path to the folder that stores the output
* *convert-to-turtle* - converts rdf file/files to turtle
** parameters:
*** ONTOLOGY_FOLDER_PATH - path to the folder containing rdf file/files
* *convert-to-rdf* - converts turtle file/files to rdf
** parameters:
*** ONTOLOGY_FOLDER_PATH - path to the folder containing turtle file/files

==== Preparing the local environment

*Prerequisites*:

* The Make utility must be installed
* Python3 must be installed

*Steps*:

. Clone the https://github.com/OP-TED/model2owl.git repository
. Execute "make install" via terminal

NOTE: If you don't have a virtual environment set up, type "make create-virtual-env" to create a virtual environment, and then activate it by typing "source model2owl-venv/bin/activate"


*Configuration*:

The model2owl configuration is a collection of 4 files that should all be in the same folder:

* *config-parameters.xsl* - main config variables
* *namespaces.xml* - add namespaces that are used in your UML model
* *umlToXsdDataTypes.xml* - mapping between uml to xsd data types
* *xsdAndRdfDataTypes.xml* - configure datatypes used

Copy the default configuration files from the https://github.com/OP-TED/model2owl/blob/master/test/ePO-default-config[ePO-default-config folder] into your chosen local configuration folder.

*Changing configuration parameters*:

To change the configuration in the config-parameters.xsl,  simply change the value of the variable.

NOTE: Do not change the values from the namespacePrefixes, umlDataTypesMapping, xsdAndRdfDataTypes variables as these will already work having one config folder with all config files.

NOTE: When changing variables make sure you modify the element retaining the same datatype (boolean, string, list).

----
#exiting variables
    <xsl:variable name="acceptableTypesForObjectProperties"
        select="('epo:Identifier', 'rdfs:Literal')"/>
    <xsl:variable name="defaultNamespaceInterpretation" select="fn:true()"/>
#Don't change to different datatypes
<xsl:variable name="defaultNamespaceInterpretation" select="'new-value'"/> ---> incorrect
----
NOTE: If the variable is a list, and you don't need any values, just leave an empty list:
----
<xsl:variable name="stereotypeValidOnAssociations" select="()"/>
----

*Namespaces configuration*:

In the namespaces.xml file you can:

* add the namespaces that you use in UML model, and
* control which should be imported in the final output.

*Example*:
----
# to add prefix you need a name and the URI
 <prefix name="foaf" value="http://xmlns.com/foaf/0.1/"/>
# to have an import statement in the final output
# add importURI attribute to the definition above
 <prefix name="dct" value="http://purl.org/dc/terms/" importURI="http://purl.org/dc/terms/"/>

#Output will have the following import statement
<owl:imports rdf:resource="http://purl.org/dc/terms/"/>
----

*XSD/RDF datatypes*:

Use the xsdAndRdfDataTypes.xml file to define the datatypes used in the UML model.

*Example*:
----
    <datatype namespace="xsd" qname="xsd:date"/>
----

*UML to XSD mappings*:

If the model uses UML datatypes, these should be mapped in the umlToXsdDataTypes.xml file.

*Example*:
----
    <mapping>
        <from  qname="epo:Date"/>
        <to  qname="xsd:date"/>
    </mapping>
----
All configuration files (see above) should be in one folder. Once the folder with the desired configurations is created, the config-proxy.xsl file (found in the root directory of this project) should be changed to point to the location of the new configuration before executing any transformations.

*Example*:
----
# Change the path to the config-parameters.xsl inside the config-proxy.xsl
# from
 <xsl:import href="test/ePO-default-config/config-parameters.xsl"/>
# to
 <xsl:import href="my-pc/user/my-config-folder/config-parameters.xsl"/>
----

==== Running transformations

After installing and creating your configuration folder, use the "make targets" command described above to transform/generate output from you XMI/XML export file. The command should be executed from the root folder of the project.

*Example*:
----
# generate lightweight ontology from the UML export (xml/xmi)
make owl-core XMI_INPUT_FILE_PATH=/home/mypc/work/model2owl/file1.xml OUTPUT_FOLDER_PATH=./my-folder
----
////
=== Using the automated online utility: model2owl-boilerplate

To use model2owl without installing or executing anything locally, the online https://github.com/meaningfy-ws/model2owl-boilerplate[model2owl boilerplate utility] has been created. The instructions are given in the repositories README.md file as well as here:

Getting Started:
This project will use model2owl to transform a UML model into a formal OWL ontology, a SHACL shape, a conventions report and glossary based on established UML conventions.

Main steps:

Fork this repository
Put your UML model/models export (XML file) in the implementation folder
Configure model2owl using config folder
Change GitHub action script available to include your ontologies
////

include::partial$feedback.adoc[]


