= Technical Information:

=== Technical Overview

The https://github.com/OP-TED/model2owl/[*model2owl*] project comprises a set of tools for transforming an UML (v2.5) model from its XMI (v2.5.1) serialisation into a formal OWL ontology, and a SHACL shape. This approach conforms to the https://semiceu.github.io/style-guide/1.0.0/index.html[SEMIC Style Guide] and with the https://github.com/meaningfy-ws/model2owl/blob/master/doc/ontology-architecture/ontology-architecture.pdf[eProcurement Ontology Architecture specification].

The UML transformation is performed using XSLT stylesheets on the assumption that the UML model conforms to the set of conventions outlined in the https://meaningfy-ws.github.io/model2owl-docs/public-review/uml/conceptual-model-conventions.html[EPO UML conventions specification]. This set of UML conventions is aligned with and extends the UML conventions specified in https://semiceu.github.io/style-guide/1.0.0/index.html[SEMIC Style Guide].

The following capabilities are implemented:

#list of what can be transformed#

#do the arrows indicate a transformation?#

* UML -> Compliance report (ideal for checking the model against the established conventions)
* UML -> Glossary (ideal for a quick overview of terminology defined)
* UML -> OWL 2 (lightweight ontology suitable as a core vocabulary)
* UML -> OWL 2 (heavyweight ontology with additional axioms suitable for reasoning purposes)
* UML -> SHACL (data shapes suitable for representing an application profile)

The documentation is constantly reviewed and aims to cover the important aspects when using these tools, including:

* The architectural setup of the project and the ontology
* The conceptual model conventions that the UML model should adhere to to generate the best possible results.
* The transformation rules applied in the process of conversion.
* The set of validation rules that realise the established conventions (and UML interpretations).

This work is developed in the context of https://github.com/eprocurementontology/eprocurementontology[eProcurement ontology project] financed by the Digital Europe Programme and led by the https://op.europa.eu/en/[Publications Office of the European Union].

The tools can be used on any other ontology that is built according to the provided https://github.com/meaningfy-ws/model2owl/blob/master/doc/ontology-architecture/ontology-architecture.pdf[modelling architecture] and xref:uml/conceptual-model-conventions.adoc[UML conceptual model conventions].

This specification establishes conventions for the interpretation of the UML-based conceptual model in the eProcurement context.



#how it works, technical overview#

== Components

xref:architecture/ontology-architecture.adoc[eProcurement ontology architecture and formalisation specifications]

xref:uml/conceptual-model-conventions.adoc[UML Conventions]

xref:transformation/uml2owl-transformation.adoc[Transfer Rules]

xref:checkers/model2owl-checkers.adoc[Verification (checkers)]


== Performing transformations: Processes and procedures

#getting started#

#Prerequisites (not provided on GitHub)#

#Resources on GitHub#

#who, why, where of use#

#Instructions: Processes and procedures#


