:doctitle: UML Conceptual Model Conventions
:doccode: m2o-main-prod-007
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: November 2023



This part of the *model2owl* project documentation describes the conventions that the UML conceptual model *should adhere to* so that the tools provided within the *model2owl* project generate the best possible derived artefacts i.e., the most complete and correct OWL ontologies and SHACL shapes.


[[sec:on-conventions]]
== UML Model Conventions

The current set of UML Model Conventions is meant to guide semantic engineers and ontology editors in producing consistent, uniform, and uniquely interpretable conceptual models. Also, it is meant to help readers of the conceptual models interpret the meaning clearly by eliminating ambiguities. With these goals achieved, the conventions are fit for implementation.

The set of guidelines is aligned with the https://joinup.ec.europa.eu/collection/semic-support-centre/news/release-semic-style-guide#:~:text=The%20SEMIC%20Style%20Guide%20is%20a%20document%20that,expert%20advice%20on%20semantic%20interoperability%20for%20public%20administrations[SEMIC style guide], extending and elaborating on it.

The guidelines provided here may be of general or technical nature. They are formulated to be understood easily by semantic engineers, to allow the implementation of automatic model checkers (see Section xref:checkers/model2owl-checkers.adoc[]) and the definition of precise transformation rules used by tools, to generate the semantic artefacts automatically (see Section xref:transformation/uml2owl-transformation.adoc[]).

The convention are organised into the following subsections:

* general conventions, which apply to multiple model components
* conventions specific to particular UML elements (Classes and their Attributes, Data Types, Enumerations, Objects, Packages)
* general conventions on UML connectors
* conventions specific to particular UML connector types (Associations, Dependencies, Generalisations, Realisations)

include::conv-general.adoc[]

include::conv-attributes.adoc[]

include::conv-attributes.adoc[]

include::conv-classes.adoc[]

include::conv-conn-association.adoc[]

include::conv-conn-dependency.adoc[]

include::conv-conn-generalization.adoc[]

include::conv-conn-realization.adoc[]

include::conv-connectors.adoc[]

include::conv-datatypes.adoc[]

include::conv-enumerations.adoc[]

include::conv-objects.adoc[]

include::conv-packages.adoc[]

//include::definitions.adoc[]


[[sec:keywords]]
== Key words for Requirement Statements

The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED", "MAY", and "OPTIONAL" in this document are to be interpreted as described in RFC 2119 [xref:references.adoc#ref:rfc2119[rfc2119]].

The key words "MUST (BUT WE KNOW YOU WON’T)", "SHOULD CONSIDER", "REALLY SHOULD NOT", "OUGHT TO", "WOULD PROBABLY", "MAY WISH TO", "COULD", "POSSIBLE", and "MIGHT" in this document are to be interpreted as described in RFC 6919 [xref:references.adoc#ref:rfc6919[rfc6919]].



include::partial$feedback.adoc[]
