:doctitle: Conventions on Attributes of uml:Class elements
:doccode: m2o-main-prod-008
:author: NPJ
:authoremail: nicole-anne.paterson-jones@ext.ec.europa.eu
:docdate: November 2023



[[sec:attributes]]
== Conventional recommendations on Attributes

[[rule:attributes-names-with-verb]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Attribute names

|{set:cellbgcolor: #f5f8fc}
*Identifier:* rule:attributes-names-with-verb

|*Statement:*
It is recommended to use a verb in the attribute name, such as "has-" or "is-".
|===

*Description:*

When creating attribute names, the convention is to use simple nouns such as "name", "weight", "colour". Attributes are a special type of relations that describe an entity in terms of its qualities.

To comply with the above convention and to increase clarity, it is recommended to employ the prefix "has-" for each attribute, even if it does not add much to the term's meaning. Therefore, using terms such as "hasName", "hasWeight" and "hasColour" is preferred.

It is recommended to use simple nouns for attribute names prepended with the verb "has-".

It is recommended to avoid duplicate attribute names across multiple classes. Unless, by design, attributes with the same name are shared across multiple classes.

// To avoid laborious mechanical work of adding the prefix, it is possible to rely on the convention that the attribute names starting with a capital letter must be read as having the "has-" prefix. It means that the transformation script will prepend the "has-" prefix to all attributes starting with a capital letter.

[[rule:attributes-multiplicity]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Attribute multiplicity

|{set:cellbgcolor: #f5f8fc}
*Identifier:* rule:attributes-multiplicity

|*Statement:*
Attributes shall be assigned cardinality specifications contextualised to the class carrying them.
|===

*Description:*

Attribute multiplicity should be specified indicating the minimum and maximum cardinality. The default [1] multiplicity shall be interpreted as unspecified, and expressed as [0..*] in the OWL model.

In special cases, a list of custom default multiplicities is defined for the transformation script. This means that some data types or classes that are used as attribute types are paired with a default multiplicity, for example "1..1", "0..1", "2..2".

[[sec:attributes-class]]
== uml:Class attributes

[[rule:attributes-datatypes]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Attribute datatypes

|{set:cellbgcolor: #f5f8fc}
*Identifier:* rule:attributes-datatypes

|*Statement:*
uml:Attribute shall be defined with generally accepted primitive datatypes.
|===

*Description:*

Each uml:Attribute must have a name and an attribute type. uml:Attribute is mostly transformed into owl:DataProperty and in some controlled cases into owl:ObjectProperty. High preference shall be given to using OWL 2 compliant https://www.w3.org/TR/xmlschema11-2/[XSD] and https://www.w3.org/TR/rdf-syntax-grammar/[RDF]  standard datatypes. [xref:uml/conv-datatypes.adoc#rule:datatypes-primitive[See convention on Primitive Data types]]

Cases where a property needs to be defined as ranging on an unknown controlled list or authority table constitute special cases. They can be expressed as uml:Attribute with the datatype `skos:Concept`. These attributes are transformed into owl:ObjectProperty in a manner similar to uml:Association.

An attribute may contain an alias that is used as an alternative label. It can be specified via uml:Tags. [xref:uml/conv-general.adoc#rule:gen-tags[See convention on uml:Tags]]

[[rule:attributes-reuse]]
|===
|{set:cellbgcolor: #a8c6f7}
 *Title:* Attribute name reuse

|{set:cellbgcolor: #f5f8fc}
*Identifier:* rule:attributes-reuse

|*Statement:*
Attribute names can be reused only as attributes in other classes, not as relations.
|===

*Description:*

It is mandatory to avoid using the same name in an attribute and in a relation unless an additional rule that handles intentional exceptions exists.

The definition and datatype, and in most cases also the multiplicity, of the attribute should be the same in all classes where it is reused.

